// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OPG.Models;

namespace OPG.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210211205001_OrderFormCreated")]
    partial class OrderFormCreated
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("OPG.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Fruit"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Vegetables"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Dairy products and eggs"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Animal products"
                        });
                });

            modelBuilder.Entity("OPG.Models.OrderForm", b =>
                {
                    b.Property<int>("OrderFormId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Address1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderPlaced")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("OrderTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ZipCode")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OrderFormId");

                    b.ToTable("OrderForms");
                });

            modelBuilder.Entity("OPG.Models.OrderFormDetail", b =>
                {
                    b.Property<int>("OrderFormDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<int>("OrderFormId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("OrderFormDetailId");

                    b.HasIndex("OrderFormId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderFormDetails");
                });

            modelBuilder.Entity("OPG.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<string>("OrderId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("OrderItemId");

                    b.HasIndex("ProductId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("OPG.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<float>("Discount")
                        .HasColumnType("real");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            Discount = 0f,
                            ImageUrl = "",
                            Name = "Apple",
                            Price = 0m
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 2,
                            Discount = 0f,
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepie.jpg",
                            Name = "Carrot",
                            Price = 0m
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 3,
                            Discount = 0f,
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepie.jpg",
                            Name = "Eggs",
                            Price = 0m
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 4,
                            Discount = 0f,
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepie.jpg",
                            Name = "Tuna",
                            Price = 0m
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 2,
                            Discount = 0f,
                            ImageUrl = "https://gillcleerenpluralsight.blob.core.windows.net/files/applepie.jpg",
                            Name = "Potato",
                            Price = 0m
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 2,
                            Discount = 0f,
                            ImageUrl = "",
                            Name = "Tomato ",
                            Price = 0m
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 2,
                            Discount = 0f,
                            ImageUrl = "",
                            Name = "Salad ",
                            Price = 0m
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 2,
                            Discount = 0f,
                            ImageUrl = "",
                            Name = "Onion",
                            Price = 0m
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 2,
                            Discount = 0f,
                            ImageUrl = "",
                            Name = "Broccoli ",
                            Price = 0m
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 1,
                            Discount = 0f,
                            ImageUrl = "",
                            Name = "Cauliflower ",
                            Price = 0m
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 2,
                            Discount = 0f,
                            ImageUrl = "",
                            Name = "Cucumber",
                            Price = 0m
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 2,
                            Discount = 0f,
                            ImageUrl = "",
                            Name = "Spinach ",
                            Price = 0m
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 2,
                            Discount = 0f,
                            ImageUrl = "",
                            Name = "Radish ",
                            Price = 0m
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 2,
                            Discount = 0f,
                            ImageUrl = "",
                            Name = "Celery ",
                            Price = 0m
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 2,
                            Discount = 0f,
                            ImageUrl = "",
                            Name = "Beans ",
                            Price = 0m
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 1,
                            Discount = 0f,
                            ImageUrl = "",
                            Name = "Pear ",
                            Price = 0m
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 1,
                            Discount = 0f,
                            ImageUrl = "",
                            Name = "Orange ",
                            Price = 0m
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 1,
                            Discount = 0f,
                            ImageUrl = "",
                            Name = "Lemon ",
                            Price = 0m
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 1,
                            Discount = 0f,
                            ImageUrl = "",
                            Name = "Strawberry ",
                            Price = 0m
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 1,
                            Discount = 0f,
                            ImageUrl = "",
                            Name = "Blackberry ",
                            Price = 0m
                        },
                        new
                        {
                            ProductId = 21,
                            CategoryId = 1,
                            Discount = 0f,
                            ImageUrl = "",
                            Name = "Raspberry ",
                            Price = 0m
                        },
                        new
                        {
                            ProductId = 22,
                            CategoryId = 1,
                            Discount = 0f,
                            ImageUrl = "",
                            Name = "Blueberry ",
                            Price = 0m
                        },
                        new
                        {
                            ProductId = 23,
                            CategoryId = 1,
                            Discount = 0f,
                            ImageUrl = "",
                            Name = "Grape ",
                            Price = 0m
                        },
                        new
                        {
                            ProductId = 24,
                            CategoryId = 1,
                            Discount = 0f,
                            ImageUrl = "",
                            Name = "Plum ",
                            Price = 0m
                        },
                        new
                        {
                            ProductId = 25,
                            CategoryId = 1,
                            Discount = 0f,
                            ImageUrl = "",
                            Name = "Watermelon ",
                            Price = 0m
                        },
                        new
                        {
                            ProductId = 26,
                            CategoryId = 3,
                            Discount = 0f,
                            ImageUrl = "",
                            Name = "Cheese ",
                            Price = 0m
                        },
                        new
                        {
                            ProductId = 27,
                            CategoryId = 3,
                            Discount = 0f,
                            ImageUrl = "",
                            Name = "Yogurt ",
                            Price = 0m
                        },
                        new
                        {
                            ProductId = 28,
                            CategoryId = 3,
                            Discount = 0f,
                            ImageUrl = "",
                            Name = "Milk ",
                            Price = 0m
                        },
                        new
                        {
                            ProductId = 29,
                            CategoryId = 1,
                            Discount = 0f,
                            ImageUrl = "",
                            Name = "Cherry",
                            Price = 0m
                        },
                        new
                        {
                            ProductId = 30,
                            CategoryId = 2,
                            Discount = 0f,
                            ImageUrl = "",
                            Name = "Eggplant ",
                            Price = 0m
                        });
                });

            modelBuilder.Entity("OPG.Models.OrderFormDetail", b =>
                {
                    b.HasOne("OPG.Models.OrderForm", "OrderForm")
                        .WithMany("OrderFormDetails")
                        .HasForeignKey("OrderFormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OPG.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OrderForm");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OPG.Models.OrderItem", b =>
                {
                    b.HasOne("OPG.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("OPG.Models.Product", b =>
                {
                    b.HasOne("OPG.Models.Category", "Category")
                        .WithMany("Product")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("OPG.Models.Category", b =>
                {
                    b.Navigation("Product");
                });

            modelBuilder.Entity("OPG.Models.OrderForm", b =>
                {
                    b.Navigation("OrderFormDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
